### ISSUE TITLE
无法出售物品

### ISSUE THREAD

**Issue by Touyko** [LinsPMStudio/BossShopPro#2]
**Describe the bug**

**To Reproduce**

**Screenshots(Optional)**

**Desktop (please complete the following information):**
 - OS: [e.g.:Windows 10 22H2]
-  Java: [e.g.:Java 8]

**Additional context**
服务端版本paper-1.19.2-142
示例bs默认菜单buyshop，执行出售物品操作，提示没有足够的物品
![image 44](https://user-images.githubusercontent.com/48090248/194250062-f40f22f8-7c06-4e9f-a000-9a56a60cbd1e.jpg)

**Comment by lijinhong11** [comment]
请问你用的什么键

**Comment by Touyko** [comment]
> 请问你按的什么键
右键

**Comment by lijinhong11** [comment]
有没有尝试去拿新的火把来卖

**Comment by Touyko** [comment]
试过不行

**Comment by lijinhong11** [comment]
那个商店文件发一下

**Comment by Touyko** [comment]
[BuyShop.zip](https://github.com/LinsPMStudio/BossShopPro/files/9724005/BuyShop.zip)

**Comment by lijinhong11** [comment]
你改一下这里，看可不可以：
```
PriceType_right: ITEM 
Price_right:
- type:TORCH
- amount:16
```
改成
```
PriceType_right: ITEM 
Price_right:
- - type:TORCH
  - amount:16
```

**Comment by Touyko** [comment]
尝试过

**Comment by lijinhong11** [comment]
重载插件了吗

**Comment by Touyko** [comment]
也没报错信息，就识别不到物品

**Comment by Touyko** [comment]
好的感谢
